# https://pre-commit.com/index.html#adding-pre-commit-plugins-to-your-project
default_language_version:
  python: python3.13
repos:
  # https://github.com/editorconfig-checker/editorconfig-checker.python?tab=readme-ov-file#usage-with-the-pre-commit-git-hooks-framework
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.2.1"
    hooks:
      - id: editorconfig-checker
        args:
          - --help

  # https://github.com/DavidAnson/markdownlint-cli2#pre-commit
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2

  # https://github.com/mrtazz/checkmake#pre-commit-usage
  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        alias: checkmake
        exclude: .*[.]mk$
        name: checkmake [Makefile]
      - id: checkmake
        alias: checkmake-module
        exclude: Makefile$
        name: checkmake [Makefile includes]
        args:
        - --config=.checkmake-module.ini

  # https://github.com/pre-commit/mirrors-mypy
  # Use hooks[].id.exclude to avoid pre-commit's list of files from overriding the --exclude arg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    - id: mypy
      # typing-related dependencies have to be installed b/c pre-commit runs in its own virtualenv
      additional_dependencies:
      - "argcomplete==3.6.2"
      - "types-requests==2.32.*"
      - "types-requests-oauthlib==2.0.*"
      exclude: ^src/python/.*$
      name: mypy-sode
      args:
      - --config-file=src/sode/python/pyproject.toml

  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
        exclude: '.*[.][1-8][.]md$'

  # https://black.readthedocs.io/en/stable/integrations/source_version_control.html#version-control-integration
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        name: black-sode
        language_version: python3.13
        args:
        - --config=src/sode/python/pyproject.toml
        - src/sode/python

  # https://pycqa.github.io/isort/docs/configuration/pre-commit.html
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort-sode
        args:
        - src/sode/python/sode
