.PHONY: default
default: all

# Programs

BREW ?= brew
PIP ?= pip
PYTHON ?= python

#. PYTHON TARGETS

#. STANDARD TARGETS

.PHONY: all
all:
	@:

.PHONY: clean
clean:
	@:

.PHONY: test
test:
	@:

#. SUPPORT TARGETS

.PHONY: homebrew-install
homebrew-install:
	$(BREW) bundle install
