name: setuptools-flat
description: Check setuptools-flat

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/setuptools-flat.yml'
      - 'src/python/setuptools-flat/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/setuptools-flat.yml'
      - 'src/python/setuptools-flat/**'
  workflow_dispatch:

env:
  python_cache: 'pipenv'
  python_version: '3.13.2'
  working_directory: ./src/python/setuptools-flat

permissions:
  contents: read

jobs:
  setuptools-flat:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: ${{ env.python_cache }}
          cache-dependency-path: ${{ env.working_directory }}/Pipfile.lock
          python-version: ${{ env.python_version }}

      - run: python --version
      - run: pip --version
      - run: pipx --version

      - run: pip install pipenv
      - run: pipenv --version
      - run: pipenv install --dev

  setuptools-flat-build:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    needs: setuptools-flat
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: ${{ env.python_cache }}
          cache-dependency-path: ${{ env.working_directory }}/Pipfile.lock
          python-version: ${{ env.python_version }}

      # Packages were already loaded from cache, but commands like pipenv et al won't be on the path
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: make

  setuptools-flat-install:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    needs: setuptools-flat-build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: ${{ env.python_cache }}
          cache-dependency-path: ${{ env.working_directory }}/Pipfile.lock
          python-version: ${{ env.python_version }}

      # Packages were already loaded from cache, but commands like pipenv et al won't be on the path
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: make install
