name: sode manuals
description: Build manuals for sode with Pandoc

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/sode-manual.yml'
      - 'src/sode/manual/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/sode-manual.yml'
      - 'src/sode/manual/**'
  workflow_dispatch:

env:
  pandoc_version: '3.2'
  working_directory: ./src/sode/manual

permissions:
  contents: read

jobs:
  sode-manual:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: pandoc/actions/setup@main
        with:
          version: ${{ env.pandoc_version }}
      - run: pandoc --version
      - run: make all
