name: sode python
description: Check sode python sources

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/sode-python.yml'
      - 'src/sode/python/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/sode-python.yml'
      - 'src/sode/python/**'
  workflow_dispatch:

env:
  python_version: '3.13.2'
  working_directory: ./src/sode/python

permissions:
  contents: read

jobs:
  sode-python:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
          cache: 'pipenv'
          cache-dependency-path: |
            ${{ env.working_directory }}/Pipfile.lock

      - run: python --version
      - run: pip --version

      - run: pip install pipenv
      - run: pipenv --version

      - run: pipenv install
